version: '3.8'

services:

  # Postgres database server
  db:
    container_name: postgres_for_v14
    image: postgres:12.5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5414:5432/tcp
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

  # Pgadmin4 
  pgadmin:
    container_name: pgadmin4_for_v14
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8114:80/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=developer@izote.net
      - PGADMIN_DEFAULT_PASSWORD=odoo
      - PGADMIN_LISTEN_PORT=80

  # Odoo Server
  web:
    container_name: odoo_v14
    image: izotecarlitos/odoo-container:14.0
    depends_on:
      - db
    ports:
      - "8014:8069"
    volumes:
      # Odoo Configuration directory
      - ./config:/etc/odoo 
      # Odoo local development
      - ./backups:/mnt/backups
      - ./extra-addons:/mnt/extra-addons
      - ./filestore:/var/lib/odoo
      # Odoo shared sources to be used by the running container
      #- ../../odoo_latest_src/community/v14/odoo:/mnt/community                      # See note 1 
      - ../../odoo_latest_src/community/v14/odoo:/usr/lib/python3/dist-packages/odoo  # See note 1
      - ../../odoo_latest_src/enterprise/v14/:/mnt/enterprise
      - ../../odoo_latest_src/themes/v14:/mnt/themes
      - ../../odoo_latest_src/appstore/v14:/mnt/appstore

    # Use this command to initialize your database with 
    # the modules of your preference
    #command: odoo
    #         --init website_sale,stock,sale_management,purchase,mass_mailing,l10n_cl,im_livechat,crm,board,account
    #         --without-demo
    #         --dev=all
    #         --database testing_db

    # Use this command to update all modules when the container starts
    #command: odoo --update all --dev=all --database testing_db

    # Use this command to update a specific module when the container starts
    #command: odoo --update testing_module --dev=all --database testing_db

volumes:
  # Postgres /var/lib/postgresql/data
  pg-data:
    driver: local
    
  # Pgadmin /var/lib/pgadmin
  pgadmin-data:
    driver: local

# Notes:
# 1) use /mnt/community in the container if you want to copy the contents from the container to the host
#    use /usr/lib/python3/dist-packages/odoo if you want to inject the sources from your host into the container
